In [1]:
import numpy as np

# 1. 创建等比数列

In [8]:
arr1 = np.logspace(0, 9, 10)  # base不写默认10
print(arr1)
print(arr1.dtype)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
float64


In [10]:
arr2 = np.logspace(0, 9, 10, base = 2, dtype = np.int64)  # base不写默认10
print(arr2)
print(arr2.dtype)

[  1   2   4   8  16  32  64 128 256 512]
int64


# 2. 创建等差数列

In [17]:
arr3 = np.linspace(1, 10, 4, endpoint = False, dtype = np.int64)
print(arr3)
print(arr3.dtype)

[1 3 5 7]
int64
