In [1]:
import numpy as np

# 1. numpy统计函数演示

In [2]:
# 1. 定义numpy对象ndaray数组
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(np.cumsum(arr1))

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [15]:
print(np.sum(arr1))
print(np.sum(arr1, axis = 0))
print(np.sum(arr1, axis = 1))
print(np.mean(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.std(arr1))


66
[12 15 18 21]
[ 6 22 38]
5.5
11
0
3.452052529534663
