In [ ]:
import numpy as np

# 1. numpy去重函数

In [ ]:
# 1. 定义数组
arr1 = np.array([[1, 2, 1], [2, 3, 5]])
print(arr1)

In [ ]:
arr2 = np.unique(arr1)
print('arr1:', arr1)
print('arr2:', arr2)

# 2. numpy排序函数

In [7]:
arr1 = np.array([[1, 2, 1], [2, 3, 5]])
print(arr1)

[[1 2 1]
 [2 3 5]]


In [9]:
arr2 = np.sort(arr1)
print('arr1:', arr1)
print('arr2:', arr2)

arr1.sort()
print('arr1:', arr1)

arr1: [[1 2 1]
 [2 3 5]]
arr2: [[1 1 2]
 [2 3 5]]
arr1: [[1 1 2]
 [2 3 5]]
